export const OBTENER_MASTER = 'OBTENER_MASTER';
export const AGREGAR_MASTER = 'AGREGAR_MASTER';
export const VALIDAR_MASTER = 'VALIDAR_MASTER';
export const MASTER_ACTUAL = 'MASTER_ACTUAL';
export const ELIMINAR_MASTER = 'ELIMINAR_MASTER';
export const MASTER_ERROR='MASTER_ERROR';;
export const EDIT_MASTER='EDIT_MASTER'

export const OBTENER_MASTER_DETAIL = 'OBTENER_MASTER_DETAIL';
export const EDIT_MASTER_DETAIL= 'EDIT_MASTER_DETAIL';
export const AGREGAR_MASTER_DETAIL = 'AGREGAR_MASTER_DETAIL';
export const MASTER_DETAIL_ACTUAL = 'MASTER_DETAIL_ACTUAL';
export const ELIMINAR_MASTER_DETAIL = 'ELIMINAR_MASTER_DETAIL';
export const MASTER_DETAIL_ERROR='MASTER_DETAIL_ERROR';;

export const OBTENER_MASTER_STATUS = 'OBTENER_MASTER_STATUS';
export const AGREGAR_MASTER_STATUS = 'AGREGAR_MASTER_STATUS';
export const SET_MASTER_STATUS_BY_ID = 'SET_MASTER_STATUS_BY_ID';
export const MASTER_STATUS_ACTUAL = 'MASTER_STATUS_ACTUAL';
export const EDIT_MASTER_STATUS= 'EDIT_MASTER_STATUS';
export const ELIMINAR_MASTER_STATUS = 'ELIMINAR_MASTER_STATUS';
export const MASTER_STATUS_ERROR='MASTER_STATUS_ERROR';

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const HIDE_SUCCES_SIGN_UP = 'HIDE_SUCCES_SIGN_UP';
export const CERRAR_SESION = 'CERRAR_SESION';

export const LOADING = 'LOADING';